project_id = "vesarikimppomvxzfxxe"

[functions.safety-tips]
verify_jwt = false

[functions.safe-routes]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.incident-report]
verify_jwt = false

[functions.threat-assessment]
verify_jwt = false
