import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { FileText, MapPin, Clock, AlertTriangle, Download, Share2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface LogEntry {
  id: string;
  trigger_type: string;
  latitude: number | null;
  longitude: number | null;
  message: string | null;
  created_at: string;
}

const triggerIcons: Record<string, string> = {
  manual: "🔴",
  shake: "📳",
  voice: "🎙️",
  stealth: "👁️‍🗨️",
};

const ActivityLog = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    if (!user) return;
    const fetchLogs = async () => {
      const { data } = await supabase
        .from("activity_logs" as any)
        .select("*")
        .order("created_at", { ascending: false })
        .limit(50) as any;
      setLogs(data ?? []);
      setLoading(false);
    };
    fetchLogs();
  }, [user]);

  const formatDate = (iso: string) => {
    const d = new Date(iso);
    return d.toLocaleDateString("en-IN", {
      day: "numeric",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const exportPDF = async () => {
    if (logs.length === 0) return;
    setExporting(true);

    try {
      const { default: jsPDF } = await import("jspdf");
      const { default: autoTable } = await import("jspdf-autotable");

      const doc = new jsPDF();

      // Header
      doc.setFontSize(20);
      doc.setTextColor(220, 38, 38);
      doc.text("Raksha — SOS Activity Report", 14, 20);

      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated: ${new Date().toLocaleString("en-IN")}`, 14, 28);
      doc.text(`Total events: ${logs.length}`, 14, 34);

      // Separator
      doc.setDrawColor(220, 38, 38);
      doc.setLineWidth(0.5);
      doc.line(14, 38, 196, 38);

      // Table
      const tableData = logs.map((log) => [
        log.trigger_type.charAt(0).toUpperCase() + log.trigger_type.slice(1),
        formatDate(log.created_at),
        log.latitude && log.longitude
          ? `${log.latitude.toFixed(4)}, ${log.longitude.toFixed(4)}`
          : "N/A",
        log.message ?? "",
      ]);

      autoTable(doc, {
        startY: 42,
        head: [["Trigger", "Date & Time", "Location", "Details"]],
        body: tableData,
        headStyles: {
          fillColor: [220, 38, 38],
          textColor: 255,
          fontStyle: "bold",
          fontSize: 9,
        },
        bodyStyles: { fontSize: 8, textColor: 50 },
        alternateRowStyles: { fillColor: [250, 245, 245] },
        columnStyles: {
          0: { cellWidth: 28 },
          1: { cellWidth: 42 },
          2: { cellWidth: 40 },
          3: { cellWidth: "auto" },
        },
        margin: { left: 14, right: 14 },
      });

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          "This document is auto-generated by Raksha for safety documentation purposes.",
          14,
          doc.internal.pageSize.height - 10
        );
        doc.text(
          `Page ${i} of ${pageCount}`,
          doc.internal.pageSize.width - 30,
          doc.internal.pageSize.height - 10
        );
      }

      const filename = `Raksha_SOS_Log_${new Date().toISOString().slice(0, 10)}.pdf`;

      // Try native share on mobile, fallback to download
      if (navigator.share && navigator.canShare) {
        const blob = doc.output("blob");
        const file = new File([blob], filename, { type: "application/pdf" });
        if (navigator.canShare({ files: [file] })) {
          await navigator.share({ files: [file], title: "Raksha SOS Activity Report" });
          toast({ title: "Shared successfully" });
          setExporting(false);
          return;
        }
      }

      doc.save(filename);
      toast({ title: "PDF downloaded", description: filename });
    } catch (err) {
      console.error("PDF export error:", err);
      toast({ title: "Export failed", description: "Could not generate PDF.", variant: "destructive" });
    }

    setExporting(false);
  };

  return (
    <div className="min-h-screen pt-20 pb-12 px-4">
      <div className="container mx-auto max-w-lg">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
              <FileText className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h1 className="font-display text-2xl font-bold text-foreground">Activity Log</h1>
              <p className="text-sm text-muted-foreground">SOS trigger history for safety documentation</p>
            </div>
          </div>

          {logs.length > 0 && (
            <button
              onClick={exportPDF}
              disabled={exporting}
              className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors disabled:opacity-50"
            >
              {exporting ? (
                <div className="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  <span className="hidden sm:inline">Export PDF</span>
                </>
              )}
            </button>
          )}
        </div>

        {loading ? (
          <div className="text-center py-16 text-muted-foreground">Loading...</div>
        ) : logs.length === 0 ? (
          <div className="glass-card p-8 text-center">
            <AlertTriangle className="w-10 h-10 text-muted-foreground/40 mx-auto mb-3" />
            <p className="text-muted-foreground font-medium">No SOS events recorded yet</p>
            <p className="text-sm text-muted-foreground/70 mt-1">Events will appear here when you trigger an SOS alert.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {logs.map((log) => (
              <div key={log.id} className="glass-card p-4 flex items-start gap-3">
                <span className="text-xl mt-0.5">{triggerIcons[log.trigger_type] ?? "🔴"}</span>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-sm font-semibold text-foreground capitalize">
                      {log.trigger_type} SOS
                    </span>
                    <span className="text-xs text-muted-foreground flex items-center gap-1 shrink-0">
                      <Clock className="w-3 h-3" />
                      {formatDate(log.created_at)}
                    </span>
                  </div>
                  {log.latitude && log.longitude && (
                    <a
                      href={`https://www.google.com/maps?q=${log.latitude},${log.longitude}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-xs text-primary hover:underline flex items-center gap-1 mt-1"
                    >
                      <MapPin className="w-3 h-3" />
                      {log.latitude.toFixed(4)}, {log.longitude.toFixed(4)}
                    </a>
                  )}
                  {log.message && (
                    <p className="text-xs text-muted-foreground mt-1">{log.message}</p>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default ActivityLog;
